const enemy0 = {
     "height":22,
     "id":37,
     "name":"enemy0",
     "properties":
        {
         "direction":"-1",
         "group":"enemies",
         "texture":"slime_image",
         "walking_distance":"80",
         "walking_speed":"50"
        },
     "propertytypes":
        {
         "direction":"string",
         "group":"string",
         "texture":"string",
         "walking_distance":"string",
         "walking_speed":"string"
        },
     "rotation":0,
     "type":"ground_enemy",
     "visible":true,
     "width":40,
     "x":185.833333333333,
     "y":295.916666666667
    };
    
    const enemy1 = {
     "height":20,
     "id":39,
     "name":"enemy1",
     "properties":
        {
         "direction":"-1",
         "group":"enemies",
         "texture":"fly_spritesheet",
         "walking_distance":"250",
         "walking_speed":"75"
        },
     "propertytypes":
        {
         "direction":"string",
         "group":"string",
         "texture":"string",
         "walking_distance":"string",
         "walking_speed":"string"
        },
     "rotation":0,
     "type":"flying_enemy",
     "visible":true,
     "width":37,
     "x":525.166666666667,
     "y":93.9166666666666
    };
    const enemy2 = {
     "height":22,
     "id":40,
     "name":"enemy2",
     "properties":
        {
         "direction":"-1",
         "group":"enemies",
         "texture":"slime_image",
         "walking_distance":"120",
         "walking_speed":"50"
        },
     "propertytypes":
        {
         "direction":"string",
         "group":"string",
         "texture":"string",
         "walking_distance":"string",
         "walking_speed":"string"
        },
     "rotation":0,
     "type":"ground_enemy",
     "visible":true,
     "width":40,
     "x":1100.5,
     "y":484.916666666667
    };
    const enemy3 =  {
     "height":20,
     "id":41,
     "name":"enemy3",
     "properties":
        {
         "direction":"-1",
         "group":"enemies",
         "texture":"fly_spritesheet",
         "walking_distance":"192",
         "walking_speed":"75"
        },
     "propertytypes":
        {
         "direction":"string",
         "group":"string",
         "texture":"string",
         "walking_distance":"string",
         "walking_speed":"string"
        },
     "rotation":0,
     "type":"flying_enemy",
     "visible":true,
     "width":37,
     "x":940.5,
     "y":105.916666666667
    }
    const enemy4 = {
     "height":20,
     "id":42,
     "name":"enemy4",
     "properties":
        {
         "direction":"-1",
         "group":"enemies",
         "texture":"fly_spritesheet",
         "walking_distance":"192",
         "walking_speed":"75"
        },
     "propertytypes":
        {
         "direction":"string",
         "group":"string",
         "texture":"string",
         "walking_distance":"string",
         "walking_speed":"string"
        },
     "rotation":0,
     "type":"flying_enemy",
     "visible":true,
     "width":37,
     "x":1198.16666666667,
     "y":105.916666666667
    }
    const enemy5 = {
     "height":20,
     "id":43,
     "name":"enemy5",
     "properties":
        {
         "direction":"1",
         "group":"enemies",
         "texture":"fly_spritesheet",
         "walking_distance":"192",
         "walking_speed":"75"
        },
     "propertytypes":
        {
         "direction":"string",
         "group":"string",
         "texture":"string",
         "walking_distance":"string",
         "walking_speed":"string"
        },
     "rotation":0,
     "type":"flying_enemy",
     "visible":true,
     "width":37,
     "x":1453.5,
     "y":105.916666666667
    };
    const enemy6 ={
     "height":22,
     "id":44,
     "name":"enemy6",
     "properties":
        {
         "direction":"1",
         "group":"enemies",
         "texture":"slime_image",
         "walking_distance":"100",
         "walking_speed":"50"
        },
     "propertytypes":
        {
         "direction":"string",
         "group":"string",
         "texture":"string",
         "walking_distance":"string",
         "walking_speed":"string"
        },
     "rotation":0,
     "type":"ground_enemy",
     "visible":true,
     "width":40,
     "x":1055.5,
     "y":677.916666666667
    };
    const enemy7 = {
     "height":22,
     "id":45,
     "name":"enemy7",
     "properties":
        {
         "direction":"1",
         "group":"enemies",
         "texture":"slime_image",
         "walking_distance":"200",
         "walking_speed":"50"
        },
     "propertytypes":
        {
         "direction":"string",
         "group":"string",
         "texture":"string",
         "walking_distance":"string",
         "walking_speed":"string"
        },
     "rotation":0,
     "type":"ground_enemy",
     "visible":true,
     "width":40,
     "x":1486.16666666667,
     "y":676.916666666667
    };

    const allEnSet = [enemy0, enemy1, enemy2, enemy3, enemy4, enemy5, enemy6, enemy7];

module.exports = allEnSet;
